# Generated by Django 5.0.6 on 2026-04-29 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CredentialOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('missing_credentials', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_overrides', to='schedules.teachingassignment')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(blank=True, max_length=160)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.credential')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='schedules.faculty')),
            ],
            options={
                'ordering': ['faculty__full_name', 'credential__name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCredentialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('acceptable_equivalents', models.ManyToManyField(blank=True, related_name='equivalent_subject_requirements', to='schedules.credential')),
                ('required_credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_requirements', to='schedules.credential')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requirements', to='schedules.subject')),
            ],
            options={
                'ordering': ['subject__code', 'required_credential__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='facultycredential',
            constraint=models.UniqueConstraint(fields=('faculty', 'credential'), name='unique_faculty_credential'),
        ),
        migrations.AddConstraint(
            model_name='subjectcredentialrequirement',
            constraint=models.UniqueConstraint(fields=('subject', 'required_credential'), name='unique_subject_credential_requirement'),
        ),
    ]
