# Generated by Django 5.0.6 on 2026-09-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def prepare_publication_history(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")
    for term_id in Schedule.objects.filter(status="PUBLISHED").values_list("term_id", flat=True).distinct():
        published = list(Schedule.objects.filter(term_id=term_id, status="PUBLISHED").order_by("-published_at", "-generated_at", "-pk"))
        if not published:
            continue
        current = published[0]
        for old in published[1:]:
            Schedule.objects.filter(pk=old.pk).update(
                status="ARCHIVED", archived_at=timezone.now(), replaced_by_id=current.pk
            )
    for schedule in Schedule.objects.all().only("pk", "generated_at"):
        Schedule.objects.filter(pk=schedule.pk).update(updated_at=schedule.generated_at)


def group_legacy_meetings(apps, schema_editor):
    Assignment = apps.get_model("schedules", "Assignment")
    Meeting = apps.get_model("schedules", "TeachingAssignment")
    parents = {}
    for meeting in Meeting.objects.all().order_by("pk"):
        key = (meeting.term_id, meeting.subject_id, meeting.section_id, meeting.faculty_id)
        parent = parents.get(key)
        if parent is None:
            parent, _ = Assignment.objects.get_or_create(
                term_id=meeting.term_id, subject_id=meeting.subject_id,
                section_id=meeting.section_id, faculty_id=meeting.faculty_id,
            )
            parents[key] = parent
        Meeting.objects.filter(pk=meeting.pk).update(assignment_id=parent.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_formdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_schedules', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='component_override',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory')], max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='faculty_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_overrides', to='schedules.faculty'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='section_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_overrides', to='schedules.section'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='subject_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_overrides', to='schedules.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(prepare_publication_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('term',), name='one_published_schedule_per_term'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.faculty'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedules.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.academicterm'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='schedules.assignment'),
        ),
        migrations.AddField(
            model_name='scheduleentryaudit',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_audits', to='schedules.scheduleentry'),
        ),
        migrations.AddField(
            model_name='scheduleentryaudit',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_audits', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleentryaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(group_legacy_meetings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('term', 'subject', 'section', 'faculty'), name='unique_parent_assignment'),
        ),
    ]
